stages:
  data_ingestion:
    cmd: python src/pipelines/data_ingestion_pipeline.py
    deps:
      - src/pipelines/data_ingestion_pipeline.py
      - src/components/data_ingestion.py
      -  src/config.yaml
    outs:
      - artifacts/data_ingestion/playground-series-s4e12.zip
      - artifacts/data_ingestion_unzipped


  data_preprocessing:
    cmd: python src/pipelines/data_preprocessing_pipeline.py
    deps:
      - src/pipelines/data_preprocessing_pipeline.py
      - src/components/data_preprocessing.py
      - src/config.yaml
    outs:
      - artifacts/preprocessed_data


  model_training:
    cmd: python src/pipelines/model_training_pipeline.py
    deps:
      - src/pipelines/model_training_pipeline.py
      - src/config.yaml
      - artifacts/preprocessed_data
    outs:
      - artifacts/models
