artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: playground-series-s4e12
  local_data_file: artifacts/data_ingestion/playground-series-s4e12.zip
  unzip_dir: &unzip_dir artifacts/data_ingestion_unzipped

data_preprocessing:
  root_dir : artifacts/preprocessed_data
  source : *unzip_dir

model_training:
    source: artifacts/preprocessed_data/train_cleaned.csv
    model_save_dir: artifacts/models
    
    
